import { JobAssignment } from '../types/staffAndJobs';

export const MOCK_JOB_ASSIGNMENTS: JobAssignment[] = [
  {
    id: 'asg-1',
    jobId: '1',
    jobCode: 'JB-APX-2026-001',
    clientName: 'Apex Holdings Ltd.',
    staffId: '2',
    staffName: 'Kabir Hasan',
    roleInJob: 'Audit Manager',
    allocationPercentage: 40,
    startDate: '2026-07-01',
    dueDate: '2026-08-31',
    workloadStatus: 'High Load',
  },
  {
    id: 'asg-2',
    jobId: '1',
    jobCode: 'JB-APX-2026-001',
    clientName: 'Apex Holdings Ltd.',
    staffId: '3',
    staffName: 'Nusrat Jahan',
    roleInJob: 'Lead Senior',
    allocationPercentage: 50,
    startDate: '2026-07-01',
    dueDate: '2026-08-31',
    workloadStatus: 'Balanced',
  },
  {
    id: 'asg-3',
    jobId: '1',
    jobCode: 'JB-APX-2026-001',
    clientName: 'Apex Holdings Ltd.',
    staffId: '5',
    staffName: 'Tahmid Rahman',
    roleInJob: 'Associate Student',
    allocationPercentage: 50,
    startDate: '2026-07-01',
    dueDate: '2026-08-31',
    workloadStatus: 'Balanced',
  },
  {
    id: 'asg-4',
    jobId: '2',
    jobCode: 'JB-SQR-2026-002',
    clientName: 'Square Pharmaceuticals',
    staffId: '2',
    staffName: 'Kabir Hasan',
    roleInJob: 'Audit Manager',
    allocationPercentage: 30,
    startDate: '2026-06-15',
    dueDate: '2026-07-25',
    workloadStatus: 'High Load',
  },
  {
    id: 'asg-5',
    jobId: '2',
    jobCode: 'JB-SQR-2026-002',
    clientName: 'Square Pharmaceuticals',
    staffId: '5',
    staffName: 'Tahmid Rahman',
    roleInJob: 'Associate Student',
    allocationPercentage: 50,
    startDate: '2026-06-15',
    dueDate: '2026-07-25',
    workloadStatus: 'Balanced',
  },
  {
    id: 'asg-6',
    jobId: '3',
    jobCode: 'JB-BEX-2026-003',
    clientName: 'Beximco Communications',
    staffId: '4',
    staffName: 'Sajid Ahmed',
    roleInJob: 'Associate Student',
    allocationPercentage: 80,
    startDate: '2026-07-01',
    dueDate: '2026-07-20',
    workloadStatus: 'Available',
  },
  {
    id: 'asg-7',
    jobId: '4',
    jobCode: 'JB-JOC-2026-004',
    clientName: 'Jamuna Oil Company',
    staffId: '3',
    staffName: 'Nusrat Jahan',
    roleInJob: 'Lead Senior',
    allocationPercentage: 50,
    startDate: '2026-07-10',
    dueDate: '2026-09-15',
    workloadStatus: 'Balanced',
  }
];
