import { AttendanceRecord, AttendanceSummary } from '../types/staffAndJobs';

export const MOCK_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: 'att-1',
    date: '2026-07-16',
    staffId: '2',
    staffName: 'Kabir Hasan',
    role: 'Manager',
    checkIn: '09:05 AM',
    checkOut: '--',
    workingHours: 4.8,
    lateMinutes: 5,
    status: 'Present',
    currentAvailability: 'Fully Allocated',
  },
  {
    id: 'att-2',
    date: '2026-07-16',
    staffId: '3',
    staffName: 'Nusrat Jahan',
    role: 'Senior',
    checkIn: '08:55 AM',
    checkOut: '--',
    workingHours: 4.9,
    lateMinutes: 0,
    status: 'Present',
    currentAvailability: 'Fully Allocated',
  },
  {
    id: 'att-3',
    date: '2026-07-16',
    staffId: '4',
    staffName: 'Sajid Ahmed',
    role: 'Article Student',
    checkIn: '09:35 AM',
    checkOut: '--',
    workingHours: 4.2,
    lateMinutes: 35,
    status: 'Late',
    currentAvailability: 'Available',
  },
  {
    id: 'att-4',
    date: '2026-07-16',
    staffId: '5',
    staffName: 'Tahmid Rahman',
    role: 'Article Student',
    checkIn: '09:00 AM',
    checkOut: '--',
    workingHours: 4.9,
    lateMinutes: 0,
    status: 'Present',
    currentAvailability: 'Available',
  },
  {
    id: 'att-5',
    date: '2026-07-16',
    staffId: '7',
    staffName: 'Farhana Yasmin',
    role: 'Tax Officer',
    status: 'On Leave',
    workingHours: 0,
    lateMinutes: 0,
    currentAvailability: 'On Leave',
  },
  {
    id: 'att-6',
    date: '2026-07-16',
    staffId: '8',
    staffName: 'Imran Khan',
    role: 'Intern',
    status: 'Absent',
    workingHours: 0,
    lateMinutes: 0,
    currentAvailability: 'Training',
  }
];

export const MOCK_ATTENDANCE_SUMMARIES: AttendanceSummary[] = [
  {
    staffId: '2',
    staffName: 'Kabir Hasan',
    role: 'Manager',
    presentCount: 21,
    lateCount: 1,
    absentCount: 0,
    leaveCount: 0,
    halfDayCount: 0,
    totalHours: 176,
    attendanceRate: 98,
  },
  {
    staffId: '3',
    staffName: 'Nusrat Jahan',
    role: 'Senior',
    presentCount: 20,
    lateCount: 0,
    absentCount: 0,
    leaveCount: 1,
    halfDayCount: 1,
    totalHours: 168,
    attendanceRate: 95,
  },
  {
    staffId: '4',
    staffName: 'Sajid Ahmed',
    role: 'Article Student',
    presentCount: 18,
    lateCount: 4,
    absentCount: 0,
    leaveCount: 0,
    halfDayCount: 0,
    totalHours: 160,
    attendanceRate: 90,
  },
  {
    staffId: '5',
    staffName: 'Tahmid Rahman',
    role: 'Article Student',
    presentCount: 22,
    lateCount: 0,
    absentCount: 0,
    leaveCount: 0,
    halfDayCount: 0,
    totalHours: 178,
    attendanceRate: 100,
  }
];
