import { Client, ClientJobSummary, ClientDocumentSummary, ClientComplianceSummary, ClientActivity, ClientService } from '../types/clients';

export const MOCK_CLIENT_JOBS: Record<string, ClientJobSummary[]> = {
  '1': [
    {
      id: 'job-1',
      code: 'AUD-APX-25',
      jobType: 'Statutory Audit',
      period: 'FY 2024-25',
      manager: 'Kabir Hasan',
      progress: 95,
      dueDate: '2026-08-31',
      status: 'Under Review',
    },
    {
      id: 'job-2',
      code: 'TX-APX-25',
      jobType: 'Income Tax',
      period: 'AY 2025-26',
      manager: 'M. F. Ahmed, FCA',
      progress: 40,
      dueDate: '2026-11-30',
      status: 'In Progress',
    },
  ],
  '2': [
    {
      id: 'job-3',
      code: 'AUD-SQR-25',
      jobType: 'Statutory Audit',
      period: 'FY 2024-25',
      manager: 'Kabir Hasan',
      progress: 100,
      dueDate: '2026-07-31',
      status: 'Completed',
    },
    {
      id: 'job-4',
      code: 'VAT-SQR-26',
      jobType: 'VAT Compliance',
      period: 'Q1 2026',
      manager: 'Sajid Ahmed',
      progress: 80,
      dueDate: '2026-07-20',
      status: 'Near Deadline',
    },
  ],
  '3': [
    {
      id: 'job-5',
      code: 'ADV-BEX-26',
      jobType: 'Advisory',
      period: 'FY 2025-26',
      manager: 'A. R. Chowdhury, FCA',
      progress: 25,
      dueDate: '2026-12-31',
      status: 'Planning',
    },
  ],
};

export const MOCK_CLIENT_DOCUMENTS: Record<string, ClientDocumentSummary[]> = {
  '1': [
    {
      id: 'doc-1',
      title: 'Audited Trial Balance v3',
      category: 'Trial Balance',
      period: 'FY 2024-25',
      requestedDate: '2026-06-15',
      receivedDate: '2026-06-20',
      status: 'Approved',
    },
    {
      id: 'doc-2',
      title: 'Fixed Asset Register Excel',
      category: 'Schedules',
      period: 'FY 2024-25',
      requestedDate: '2026-06-22',
      status: 'Pending',
    },
  ],
  '2': [
    {
      id: 'doc-3',
      title: 'VAT-9.1 Return Copy May 2026',
      category: 'Tax Filing',
      period: 'May 2026',
      requestedDate: '2026-06-10',
      receivedDate: '2026-06-12',
      status: 'Approved',
    },
  ],
};

export const MOCK_CLIENT_COMPLIANCE: Record<string, ClientComplianceSummary[]> = {
  '1': [
    {
      id: 'comp-1',
      filingType: 'Annual RJSC Return',
      period: '2025',
      dueDate: '2026-09-30',
      status: 'Pending',
      responsiblePerson: 'Kabir Hasan',
    },
    {
      id: 'comp-2',
      filingType: 'Corporate Tax Return',
      period: 'AY 2025-26',
      dueDate: '2026-11-30',
      status: 'Pending',
      responsiblePerson: 'M. F. Ahmed, FCA',
    },
  ],
  '2': [
    {
      id: 'comp-3',
      filingType: 'VAT Monthly Return',
      period: 'June 2026',
      dueDate: '2026-07-15',
      status: 'Completed',
      responsiblePerson: 'Sajid Ahmed',
    },
  ],
};

export const MOCK_CLIENT_SERVICES: Record<string, ClientService[]> = {
  '1': [
    {
      id: 'srv-1',
      name: 'Statutory Audit',
      status: 'Active',
      assignedTeam: ['Kabir Hasan', 'Tahmid Rahman'],
      startDate: '2021-06-01',
      lastCompletedJob: 'AUD-APX-24',
      nextRequiredAction: 'Review Sampling Queries',
    },
    {
      id: 'srv-2',
      name: 'Income Tax',
      status: 'Active',
      assignedTeam: ['M. F. Ahmed', 'Nusrat Jahan'],
      startDate: '2021-11-15',
      nextRequiredAction: 'Draft Tax Assessment Schedule',
    },
  ],
  '2': [
    {
      id: 'srv-3',
      name: 'Statutory Audit',
      status: 'Active',
      assignedTeam: ['Kabir Hasan', 'Kamrul Islam'],
      startDate: '2019-01-01',
      lastCompletedJob: 'AUD-SQR-25',
      nextRequiredAction: 'Final Signing & Dispatch',
    },
  ],
};

export const MOCK_CLIENT_ACTIVITIES: Record<string, ClientActivity[]> = {
  '1': [
    {
      id: 'act-1',
      clientId: '1',
      action: 'Details updated',
      actor: 'Md. Zahirul Islam',
      timestamp: '2026-07-10 14:30',
      details: 'Updated BIN registration number and primary contact designation.',
    },
    {
      id: 'act-2',
      clientId: '1',
      action: 'Communication logged',
      actor: 'A. R. Chowdhury, FCA',
      timestamp: '2026-07-08 11:15',
      details: 'Logged meeting minutes regarding NBR audit assessment.',
    },
  ],
  '2': [
    {
      id: 'act-3',
      clientId: '2',
      action: 'Job created',
      actor: 'Kabir Hasan',
      timestamp: '2026-07-15 09:00',
      details: 'Created VAT-SQR-26 Compliance engagement.',
    },
  ],
};

export const INITIAL_MOCK_CLIENTS: Client[] = [
  {
    id: '1',
    name: 'Apex Holdings Ltd.',
    tradingName: 'Apex Holdings',
    code: 'APEX-01',
    type: 'Private Limited Company',
    registrationNumber: 'C-98124/2018',
    incorporationDate: '2018-04-12',
    financialYearEnd: 'June 30',
    industry: 'Manufacturing & Textiles',
    businessDescription: 'A major conglomerate involved in textile export, logistics, and real estate development across Bangladesh.',
    tin: '482910381920',
    bin: '001928374-0101',
    vatCircle: 'Circle-2 (Tejgaon)',
    taxCircle: 'Circle-11 (Large Taxpayers Unit)',
    rjscRegistrationNumber: 'REG-98124C',
    regulatoryBody: 'NBR, RJSC, BIDA',
    listedStatus: 'Unlisted',
    primaryContact: {
      name: 'Tanvir Hossain',
      designation: 'Chief Financial Officer',
      email: 'cfo@apexholdings.com',
      phone: '+880-1711-234567',
      altPhone: '+880-2-9812345',
      preferredMethod: 'Email',
    },
    additionalContacts: [
      {
        name: 'Asif Rahman',
        designation: 'Finance Manager',
        email: 'asif@apexholdings.com',
        phone: '+880-1819-876543',
        preferredMethod: 'WhatsApp',
      },
    ],
    officeAddress: 'Apex House, Plot 14, Road 12, Gulshan-1, Dhaka-1212',
    registeredAddress: 'East Chandora, Kaliakoir, Gazipur',
    website: 'https://www.apexholdings.com',
    services: ['Statutory Audit', 'Income Tax', 'VAT', 'RJSC'],
    assignedPartner: 'A. R. Chowdhury, FCA',
    assignedManager: 'Kabir Hasan',
    assignedSenior: 'Tahmid Rahman',
    engagementStartDate: '2021-06-01',
    portalRequired: true,
    portalContactEmail: 'cfo@apexholdings.com',
    portalRolePlaceholder: 'Client Admin',
    portalStatus: 'Active',
    status: 'Active',
    lastActivity: '2026-07-15 14:30',
  },
  {
    id: '2',
    name: 'Square Pharmaceuticals PLC',
    tradingName: 'Square Pharma',
    code: 'SQR-01',
    type: 'Public Limited Company',
    registrationNumber: 'C-10294/1984',
    incorporationDate: '1984-06-25',
    financialYearEnd: 'June 30',
    industry: 'Pharmaceuticals & healthcare',
    businessDescription: 'The leading pharmaceutical manufacturer in Bangladesh, exporting generic formulations worldwide.',
    tin: '102938475610',
    bin: '000102934-0202',
    vatCircle: 'Circle-1 (Uttara)',
    taxCircle: 'Circle-1 (Large Taxpayers Unit)',
    rjscRegistrationNumber: 'REG-10294C',
    regulatoryBody: 'NBR, RJSC, BSEC, DGDA',
    listedStatus: 'Listed',
    primaryContact: {
      name: 'Sardar Zainuddin',
      designation: 'Director of Finance',
      email: 'szain@squarepharma.com',
      phone: '+880-1713-987654',
      preferredMethod: 'Email',
    },
    officeAddress: 'Square Centre, 48 Mohakhali C/A, Dhaka-1212',
    registeredAddress: 'Sreepur, Gazipur',
    website: 'https://www.squarepharma.com.bd',
    services: ['Statutory Audit', 'VAT', 'Advisory'],
    assignedPartner: 'S. K. Nandy, FCA',
    assignedManager: 'Kabir Hasan',
    assignedSenior: 'Kamrul Islam',
    engagementStartDate: '2019-01-01',
    portalRequired: true,
    portalContactEmail: 'szain@squarepharma.com',
    portalRolePlaceholder: 'Management Contact',
    portalStatus: 'Active',
    status: 'Active',
    lastActivity: '2026-07-16 11:20',
  },
  {
    id: '3',
    name: 'Beximco Communications Ltd.',
    tradingName: 'Beximco Comm',
    code: 'BEX-01',
    type: 'Private Limited Company',
    registrationNumber: 'C-77412/2014',
    incorporationDate: '2014-08-05',
    financialYearEnd: 'December 31',
    industry: 'Telecommunications & Media',
    businessDescription: 'Provider of satellite direct-to-home (DTH) TV services and high-speed broadband infrastructures.',
    tin: '382910481928',
    bin: '002938475-0303',
    vatCircle: 'Circle-5 (Dhanmondi)',
    taxCircle: 'Circle-15 (Dhaka)',
    rjscRegistrationNumber: 'REG-77412C',
    regulatoryBody: 'NBR, RJSC, BTRC',
    listedStatus: 'Unlisted',
    primaryContact: {
      name: 'Rahat Chowdhury',
      designation: 'General Manager (Accounts)',
      email: 'rahat.c@beximco.net',
      phone: '+880-1911-345678',
      preferredMethod: 'Phone',
    },
    officeAddress: 'Beximco Media Center, Level 4, 149 Tejgaon I/A, Dhaka-1208',
    registeredAddress: 'Beximco Industrial Park, Sarabo, Kashimpur, Gazipur',
    website: 'https://www.beximco.org',
    services: ['Advisory', 'Income Tax'],
    assignedPartner: 'A. R. Chowdhury, FCA',
    assignedManager: 'M. F. Ahmed, FCA',
    portalRequired: false,
    portalStatus: 'Not Invited',
    status: 'Pending Onboarding',
    lastActivity: '2026-07-12 10:00',
  },
  {
    id: '4',
    name: 'Shasthya Foundation Bangladesh',
    tradingName: 'Shasthya NGO',
    code: 'SHAS-NGO',
    type: 'NGO',
    registrationNumber: 'NGO-88392/2020',
    incorporationDate: '2020-02-15',
    financialYearEnd: 'December 31',
    industry: 'Non-profit & Community Health',
    businessDescription: 'National non-governmental organization focused on providing maternal health support in rural sub-districts.',
    tin: '773910293847',
    regulatoryBody: 'NGO Affairs Bureau, MRA',
    primaryContact: {
      name: 'Dr. Nusrat Zaman',
      designation: 'Executive Director',
      email: 'nusrat.zaman@shasthya.org',
      phone: '+880-1715-112233',
      preferredMethod: 'WhatsApp',
    },
    officeAddress: 'House 42, Road 5, Sector 3, Uttara, Dhaka-1230',
    services: ['Statutory Audit', 'Company Secretarial'],
    assignedPartner: 'M. F. Ahmed, FCA',
    portalRequired: true,
    portalContactEmail: 'nusrat.zaman@shasthya.org',
    portalRolePlaceholder: 'Client Admin',
    portalStatus: 'Invitation Prepared',
    status: 'Active',
    lastActivity: '2026-07-01 16:45',
  },
  {
    id: '5',
    name: 'Navana Motors Limited',
    tradingName: 'Navana Motors',
    code: 'NAV-02',
    type: 'Private Limited Company',
    registrationNumber: 'C-55410/1990',
    incorporationDate: '1990-05-18',
    financialYearEnd: 'June 30',
    industry: 'Automotive & Assembly',
    businessDescription: 'Importers and distributors of premium automobiles, spares, and service equipment.',
    tin: '992019485763',
    primaryContact: {
      name: 'Mustafa Al-Hasan',
      designation: 'Finance Controller',
      email: 'mustafa@navanamotors.com',
      phone: '+880-1712-445566',
      preferredMethod: 'Email',
    },
    officeAddress: 'Navana Tower, Level 8, 45 Gulshan Avenue, Dhaka-1212',
    services: ['Accounting', 'Payroll'],
    assignedPartner: 'S. K. Nandy, FCA',
    portalRequired: false,
    portalStatus: 'Not Invited',
    status: 'Inactive',
    lastActivity: '2026-05-20 14:00',
  }
];
