import { JobDocument } from '../types/staffAndJobs';

export const MOCK_JOB_DOCUMENTS: JobDocument[] = [
  {
    id: 'doc-101',
    clientId: '1',
    clientName: 'Apex Holdings Ltd.',
    jobId: '1',
    jobTitle: 'Statutory Audit FY 2025-26',
    documentTitle: 'Trial Balance Apex Holdings.xlsx',
    category: 'Trial Balance',
    requestedDate: '2026-07-02',
    dueDate: '2026-07-15',
    receivedDate: '2026-07-14',
    ownerId: '3',
    ownerName: 'Nusrat Jahan',
    status: 'Received',
  },
  {
    id: 'doc-102',
    clientId: '3',
    clientName: 'Beximco Communications',
    jobId: '3',
    jobTitle: 'RJSC Annual Returns Filing',
    documentTitle: 'Articles of Association Beximco.pdf',
    category: 'Legal Documents',
    requestedDate: '2026-07-01',
    dueDate: '2026-07-10',
    receivedDate: '2026-07-08',
    ownerId: '4',
    ownerName: 'Sajid Ahmed',
    status: 'Accepted Preview',
  },
  {
    id: 'doc-103',
    clientId: '1',
    clientName: 'Apex Holdings Ltd.',
    jobId: '1',
    jobTitle: 'Statutory Audit FY 2025-26',
    documentTitle: 'Bank Certificate June2026.pdf',
    category: 'Confirmations',
    requestedDate: '2026-07-05',
    dueDate: '2026-07-18',
    receivedDate: '2026-07-15',
    ownerId: '5',
    ownerName: 'Tahmid Rahman',
    status: 'Under Review',
  },
  {
    id: 'doc-104',
    clientId: '2',
    clientName: 'Square Pharmaceuticals',
    jobId: '2',
    jobTitle: 'Internal Audit Q2',
    documentTitle: 'Physical Inventory Verification Report 2026.pdf',
    category: 'Audit Evidence',
    requestedDate: '2026-07-10',
    dueDate: '2026-07-20',
    ownerId: '2',
    ownerName: 'Kabir Hasan',
    status: 'Requested',
  }
];
