import { Job } from '../types/staffAndJobs';

export const MOCK_JOBS_REGISTER: Job[] = [
  {
    id: '1',
    jobCode: 'JB-APX-2026-001',
    clientName: 'Apex Holdings Ltd.',
    clientId: '1',
    serviceType: 'Statutory Audit',
    period: 'FY 2025-26',
    partnerId: '1',
    partnerName: 'A. R. Chowdhury, FCA',
    managerId: '2',
    managerName: 'Kabir Hasan',
    teamMemberIds: ['3', '5'],
    teamMembersText: 'Nusrat Jahan, Tahmid Rahman',
    progress: 45,
    startDate: '2026-07-01',
    dueDate: '2026-08-31',
    status: 'In Progress',
    priority: 'High',
    description: 'Complete statutory financial audit as per Companies Act 1994 and International Standards on Auditing (ISA).',
    requiredDocuments: ['Trial Balance', 'General Ledger', 'Bank Confirmations', 'Fixed Asset Schedule', 'VAT Returns'],
    reviewLevel: 'Double (Manager & Partner)',
  },
  {
    id: '2',
    jobCode: 'JB-SQR-2026-002',
    clientName: 'Square Pharmaceuticals',
    clientId: '2',
    serviceType: 'Internal Audit',
    period: 'Q2 2026',
    partnerId: '1',
    partnerName: 'A. R. Chowdhury, FCA',
    managerId: '2',
    managerName: 'Kabir Hasan',
    teamMemberIds: ['5'],
    teamMembersText: 'Tahmid Rahman',
    progress: 80,
    startDate: '2026-06-15',
    dueDate: '2026-07-25',
    status: 'In Progress',
    priority: 'High',
    description: 'Perform operational efficiency checks on warehouse inventory systems and sales distribution controls.',
    requiredDocuments: ['Stock ledger', 'Dispatch records', 'Physical verification sheets'],
    reviewLevel: 'Manager',
  },
  {
    id: '3',
    jobCode: 'JB-BEX-2026-003',
    clientName: 'Beximco Communications',
    clientId: '3',
    serviceType: 'RJSC Compliance',
    period: 'FY 2025-26',
    partnerId: '1',
    partnerName: 'A. R. Chowdhury, FCA',
    managerId: '2',
    managerName: 'Kabir Hasan',
    teamMemberIds: ['4'],
    teamMembersText: 'Sajid Ahmed',
    progress: 95,
    startDate: '2026-07-01',
    dueDate: '2026-07-20',
    status: 'Under Review',
    priority: 'Normal',
    description: 'Assemble documentation and submit Annual Return (Form XII) and Schedule X filings to RJSC portal.',
    requiredDocuments: ['Form XII', 'AGM Minutes', 'Audited Accounts'],
    reviewLevel: 'Manager',
  },
  {
    id: '4',
    jobCode: 'JB-JOC-2026-004',
    clientName: 'Jamuna Oil Company',
    clientId: '4',
    serviceType: 'Tax Representation',
    period: 'Assessment Year 2026-27',
    partnerId: '1',
    partnerName: 'A. R. Chowdhury, FCA',
    managerId: '2',
    managerName: 'Kabir Hasan',
    teamMemberIds: ['3'],
    teamMembersText: 'Nusrat Jahan',
    progress: 0,
    startDate: '2026-07-10',
    dueDate: '2026-09-15',
    status: 'Planning',
    priority: 'High',
    description: 'Prepare tax computations, draft representations on disputed points, and attend hearings at NBR.',
    requiredDocuments: ['Assessment order', 'Income Tax returns draft', 'Previous tax files'],
    reviewLevel: 'Double (Manager & Partner)',
  },
  {
    id: '5',
    jobCode: 'JB-NAV-2026-005',
    clientName: 'Navana Motors',
    clientId: '5',
    serviceType: 'Special Purpose Audit',
    period: 'Interim 2026',
    partnerId: '1',
    partnerName: 'A. R. Chowdhury, FCA',
    managerId: '2',
    managerName: 'Kabir Hasan',
    teamMemberIds: ['5'],
    teamMembersText: 'Tahmid Rahman',
    progress: 100,
    startDate: '2026-06-01',
    dueDate: '2026-07-10',
    status: 'Completed',
    priority: 'Normal',
    description: 'Review of accounts receivable balances and identify bad debt provisions for standard reconciliation purposes.',
    requiredDocuments: ['Receivable aging report', 'Customer balance confirmations', 'Sales ledgers'],
    reviewLevel: 'Partner',
  }
];
