import { ReviewQueueItem } from '../types/staffAndJobs';

export const MOCK_REVIEW_QUEUE: ReviewQueueItem[] = [
  {
    id: 'rev-1',
    itemTitle: 'Apex Draft Accounts Review',
    type: 'Working Paper',
    clientId: '1',
    clientName: 'Apex Holdings Ltd.',
    jobId: '1',
    jobTitle: 'Statutory Audit FY 2025-26',
    preparedById: '3',
    preparedByName: 'Nusrat Jahan',
    reviewerId: '2',
    reviewerName: 'Kabir Hasan (Manager)',
    submittedDate: '2026-07-16',
    priority: 'High',
    status: 'Submitted',
    referenceId: '1',
  },
  {
    id: 'rev-2',
    itemTitle: 'Beximco Audit Planning Memorandum',
    type: 'Task Submission',
    clientId: '3',
    clientName: 'Beximco Communications',
    jobId: '3',
    jobTitle: 'RJSC Annual Returns Filing',
    preparedById: '2',
    preparedByName: 'Kabir Hasan',
    reviewerId: '1',
    reviewerName: 'A. R. Chowdhury (Partner)',
    submittedDate: '2026-07-15',
    priority: 'Normal',
    status: 'Under Review',
    referenceId: '3',
  },
  {
    id: 'rev-3',
    itemTitle: 'Form XII Filing Compliance Signature',
    type: 'Finalization Checklist',
    clientId: '3',
    clientName: 'Beximco Communications',
    jobId: '3',
    jobTitle: 'RJSC Annual Returns Filing',
    preparedById: '4',
    preparedByName: 'Sajid Ahmed',
    reviewerId: '2',
    reviewerName: 'Kabir Hasan (Manager)',
    submittedDate: '2026-07-14',
    priority: 'High',
    status: 'Approved Demo',
    referenceId: '4',
  }
];
