import { StaffMember, StaffProfile } from '../types/staffAndJobs';

export const MOCK_STAFF_MEMBERS: StaffMember[] = [
  {
    id: '1',
    staffCode: 'EMP-001',
    name: 'A. R. Chowdhury, FCA',
    email: 'ar.chowdhury@famesr.com',
    mobile: '+880-1711-123456',
    role: 'Partner',
    status: 'Active',
    department: 'Management',
    joiningDate: '2015-06-01',
    availability: 'Partially Allocated',
    attendanceStatus: 'Present',
    performanceScore: 98,
  },
  {
    id: '2',
    staffCode: 'EMP-002',
    name: 'Kabir Hasan',
    email: 'kabir.hasan@famesr.com',
    mobile: '+880-1819-234567',
    role: 'Manager',
    status: 'Active',
    department: 'Audit & Assurance',
    assignedManager: 'A. R. Chowdhury, FCA',
    joiningDate: '2019-03-15',
    availability: 'Fully Allocated',
    attendanceStatus: 'Present',
    performanceScore: 94,
  },
  {
    id: '3',
    staffCode: 'EMP-003',
    name: 'Nusrat Jahan',
    email: 'nusrat.jahan@famesr.com',
    mobile: '+880-1612-345678',
    role: 'Senior',
    status: 'Active',
    department: 'Audit & Assurance',
    assignedManager: 'Kabir Hasan',
    joiningDate: '2021-11-01',
    availability: 'Fully Allocated',
    attendanceStatus: 'Present',
    performanceScore: 88,
  },
  {
    id: '4',
    staffCode: 'STU-004',
    name: 'Sajid Ahmed',
    email: 'sajid.ahmed@famesr.com',
    mobile: '+880-1515-987654',
    role: 'Article Student',
    status: 'Active',
    department: 'Tax & Compliance',
    assignedManager: 'Kabir Hasan',
    joiningDate: '2023-01-10',
    availability: 'Available',
    attendanceStatus: 'Late',
    performanceScore: 82,
    articleshipYear: 2,
  },
  {
    id: '5',
    staffCode: 'STU-005',
    name: 'Tahmid Rahman',
    email: 'tahmid.rahman@famesr.com',
    mobile: '+880-1911-876543',
    role: 'Article Student',
    status: 'Active',
    department: 'Audit & Assurance',
    assignedManager: 'Kabir Hasan',
    joiningDate: '2023-05-20',
    availability: 'Available',
    attendanceStatus: 'Present',
    performanceScore: 85,
    articleshipYear: 1,
  },
  {
    id: '6',
    staffCode: 'EMP-006',
    name: 'Rashedul Bari',
    email: 'rashed.bari@famesr.com',
    mobile: '+880-1712-999888',
    role: 'Super Admin',
    status: 'Active',
    department: 'IT & Administration',
    joiningDate: '2018-01-15',
    availability: 'Available',
    attendanceStatus: 'Present',
    performanceScore: 90,
  },
  {
    id: '7',
    staffCode: 'EMP-007',
    name: 'Farhana Yasmin',
    email: 'farhana.yasmin@famesr.com',
    mobile: '+880-1811-777666',
    role: 'Tax Officer',
    status: 'On Leave',
    department: 'Tax & Compliance',
    assignedManager: 'A. R. Chowdhury, FCA',
    joiningDate: '2020-08-01',
    availability: 'On Leave',
    attendanceStatus: 'On Leave',
    performanceScore: 86,
  },
  {
    id: '8',
    staffCode: 'STU-008',
    name: 'Imran Khan',
    email: 'imran.khan@famesr.com',
    mobile: '+880-1715-666555',
    role: 'Intern',
    status: 'Suspended',
    department: 'VAT Officer',
    assignedManager: 'Nusrat Jahan',
    joiningDate: '2024-02-01',
    availability: 'Training',
    attendanceStatus: 'Absent',
    performanceScore: 65,
  }
];

export const MOCK_STAFF_PROFILES: Record<string, StaffProfile> = {
  '1': {
    staffId: '1',
    presentAddress: 'House 14, Road 4, Dhanmondi, Dhaka',
    permanentAddress: 'Village: Uttarpara, P.O. Chandpur, Comilla',
    emergencyContact: { name: 'Sultana Chowdhury', relation: 'Spouse', phone: '+880-1711-222333' },
    dateOfBirth: '1978-04-12',
    education: 'M.Com in Accounting (Dhaka University), FCA (ICAB)',
    skills: ['Statutory Auditing', 'Financial Modeling', 'Corporate Governance', 'Strategic Tax Planning'],
    softwareProficiency: ['TallyPrime', 'QuickBooks Online', 'Excel Expert', 'Caseware Audit'],
    specialization: ['Banking Sector Audits', 'Group Consolidation', 'IPO Advisory'],
    currentWorkload: 'Overseeing 4 Group Audits',
  },
  '2': {
    staffId: '2',
    presentAddress: 'Apartment 4B, Sheltech Plaza, Mirpur, Dhaka',
    permanentAddress: 'Ward 3, Netrokona Sadar, Netrokona',
    emergencyContact: { name: 'Abul Hasan', relation: 'Father', phone: '+880-1819-111222' },
    dateOfBirth: '1991-08-22',
    education: 'BBA & MBA in Finance (Dhaka University), ACA (ICAB - Qualified)',
    skills: ['Audit Execution', 'Team Leadership', 'IFRS Compliance', 'Financial Analysis'],
    softwareProficiency: ['Excel Expert', 'SAP ERP', 'Xero', 'TallyPlus'],
    specialization: ['Manufacturing Audits', 'Deferred Tax Estimations', 'RJSC Regulatory Filings'],
    currentWorkload: '3 Active Audit Assignments',
  },
  '3': {
    staffId: '3',
    presentAddress: 'House 56, Block E, Banani, Dhaka',
    permanentAddress: 'P.O. Ghorashal, Narsingdi',
    emergencyContact: { name: 'Nawaz Sharif', relation: 'Brother', phone: '+880-1612-444555' },
    dateOfBirth: '1995-12-05',
    education: 'B.Sc in Economics (NSU), ICAB Professional Level Passed',
    skills: ['Vouching & Sampling', 'Substantive Analytical Procedures', 'VAT Calculation'],
    softwareProficiency: ['Excel Intermediate', 'QuickBooks', 'Xero'],
    specialization: ['Ready-made Garments (RMG) Audits', 'Local VAT Return filings'],
    currentWorkload: '2 Active Audits, 1 Tax Retainer',
  },
  '4': {
    staffId: '4',
    presentAddress: '24/A Bashundhara R/A, Dhaka',
    permanentAddress: 'Mymensingh Sadar, Mymensingh',
    emergencyContact: { name: 'Tahmina Begum', relation: 'Mother', phone: '+880-1515-333222' },
    dateOfBirth: '2000-05-18',
    education: 'BBA in Accounting & Information Systems (Dhaka University)',
    skills: ['Bookkeeping', 'RJSC Form Preparation', 'Tax Return Compilation'],
    softwareProficiency: ['Excel Intermediate', 'TallyPrime', 'Google Sheets'],
    specialization: ['Company Incorporation Processes', 'Individual Tax Filings'],
    articleshipRegNo: 'REG-ICAB-2023-9988',
    articleshipStartDate: '2023-01-10',
    articleshipExpectedEnd: '2026-01-09',
    principalPartner: 'A. R. Chowdhury, FCA',
    examLeaveEligibility: 'Eligible for 45 days of study leave in November 2026',
    currentWorkload: 'Assisting on Square Pharma Tax Return',
  },
  '5': {
    staffId: '5',
    presentAddress: 'Sector 11, Uttara, Dhaka',
    permanentAddress: 'Feni Sadar, Feni',
    emergencyContact: { name: 'M. Rahman', relation: 'Father', phone: '+880-1911-555444' },
    dateOfBirth: '2001-02-28',
    education: 'BBA in Finance (Jahangirnagar University)',
    skills: ['Bank Confirmation Dispatch', 'Physical Inventory Verification', 'Vouching'],
    softwareProficiency: ['Excel Basic', 'MS Word', 'Google Docs'],
    specialization: ['Service Sector Auditing', 'Inventory Counts'],
    articleshipRegNo: 'REG-ICAB-2023-1122',
    articleshipStartDate: '2023-05-20',
    articleshipExpectedEnd: '2026-05-19',
    principalPartner: 'A. R. Chowdhury, FCA',
    examLeaveEligibility: 'Eligible for 30 days of study leave in May 2026',
    currentWorkload: 'Assisting on Apex Holdings Inventory Audit',
  },
};
