import { StaffTask } from '../types/staffAndJobs';

export const MOCK_STAFF_TASKS: StaffTask[] = [
  {
    id: '1',
    taskCode: 'TSK-2026-001',
    title: 'Drafting Planning Memorandum',
    description: 'Perform preliminary analytical review, document risk factors, and draft the planning memo for partner review.',
    clientId: '1',
    clientName: 'Apex Holdings Ltd.',
    jobId: '1',
    jobTitle: 'Statutory Audit FY 2025-26',
    assigneeId: '3',
    assigneeName: 'Nusrat Jahan',
    reviewerId: '2',
    reviewerName: 'Kabir Hasan',
    priority: 'High',
    startDate: '2026-07-01',
    dueDate: '2026-07-20',
    estimatedHours: 12,
    progress: 90,
    status: 'In Progress',
    checklist: [
      { id: 'c1', item: 'Request trial balance and last year accounts', completed: true },
      { id: 'c2', item: 'Conduct preliminary ratio calculations', completed: true },
      { id: 'c3', item: 'Draft audit risk assessment table', completed: true },
      { id: 'c4', item: 'Obtain partner sign-off on materiality threshold', completed: false },
    ],
  },
  {
    id: '2',
    taskCode: 'TSK-2026-002',
    title: 'Verifying Cash & Bank Balances',
    description: 'Dispatch circularization letters to banks, track incoming certificates, and reconcile bank accounts with ledger.',
    clientId: '1',
    clientName: 'Apex Holdings Ltd.',
    jobId: '1',
    jobTitle: 'Statutory Audit FY 2025-26',
    assigneeId: '5',
    assigneeName: 'Tahmid Rahman',
    reviewerId: '3',
    reviewerName: 'Nusrat Jahan',
    priority: 'Normal',
    startDate: '2026-07-05',
    dueDate: '2026-07-22',
    estimatedHours: 8,
    progress: 50,
    status: 'In Progress',
    checklist: [
      { id: 'b1', item: 'Confirm complete bank list from trial balance', completed: true },
      { id: 'b2', item: 'Draft bank confirmation letters', completed: true },
      { id: 'b3', item: 'Obtain client signatures and send post', completed: false },
      { id: 'b4', item: 'Verify balance confirmations against ledger', completed: false },
    ],
  },
  {
    id: '3',
    taskCode: 'TSK-2026-003',
    title: 'Review Trial Balance & Ledger',
    description: 'Verify general ledger postings, trace balances from sub-ledgers, and review journal entry adjustments.',
    clientId: '2',
    clientName: 'Square Pharmaceuticals',
    jobId: '2',
    jobTitle: 'Internal Audit Q2',
    assigneeId: '2',
    assigneeName: 'Kabir Hasan',
    reviewerId: '1',
    reviewerName: 'A. R. Chowdhury, FCA',
    priority: 'High',
    startDate: '2026-07-10',
    dueDate: '2026-07-18',
    estimatedHours: 15,
    progress: 80,
    status: 'In Progress',
    checklist: [
      { id: 't1', item: 'Upload trial balance to analytical tool', completed: true },
      { id: 't2', item: 'Investigate significant journal entries', completed: true },
      { id: 't3', item: 'Compare Q2 actuals against budget', completed: true },
      { id: 't4', item: 'Identify manual postings above threshold', completed: false },
    ],
  },
  {
    id: '4',
    taskCode: 'TSK-2026-004',
    title: 'Prepare RJSC Form XII filing',
    description: 'Draft Board Resolution, assemble list of directors, and prepare RJSC Form XII for returns filing.',
    clientId: '3',
    clientName: 'Beximco Communications',
    jobId: '3',
    jobTitle: 'RJSC Annual Returns Filing',
    assigneeId: '4',
    assigneeName: 'Sajid Ahmed',
    reviewerId: '2',
    reviewerName: 'Kabir Hasan',
    priority: 'Normal',
    startDate: '2026-07-01',
    dueDate: '2026-07-14',
    estimatedHours: 6,
    progress: 100,
    status: 'Completed',
    checklist: [
      { id: 'r1', item: 'Get list of active directors and shareholdings', completed: true },
      { id: 'r2', item: 'Draft minutes of the AGM', completed: true },
      { id: 'r3', item: 'Prepare Form XII schedule', completed: true },
    ],
  },
  {
    id: '5',
    taskCode: 'TSK-2026-005',
    title: 'Tax Computation Review',
    description: 'Review corporate tax calculation, tax depreciation allowances, and deferred tax liability reconciliations.',
    clientId: '4',
    clientName: 'Jamuna Oil Company',
    jobId: '4',
    jobTitle: 'Tax Assessment Representation',
    assigneeId: '3',
    assigneeName: 'Nusrat Jahan',
    reviewerId: '1',
    reviewerName: 'A. R. Chowdhury, FCA',
    priority: 'High',
    startDate: '2026-07-12',
    dueDate: '2026-07-29',
    estimatedHours: 16,
    progress: 0,
    status: 'Draft',
    checklist: [
      { id: 'tx1', item: 'Obtain current tax provision draft', completed: false },
      { id: 'tx2', item: 'Calculate temporary differences as per IAS 12', completed: false },
      { id: 'tx3', item: 'Verify minimum tax applicability under section 82C', completed: false },
    ],
  },
];
