import { WorkLog } from '../types/staffAndJobs';

export const MOCK_WORK_LOGS: WorkLog[] = [
  {
    id: 'wl-1',
    date: '2026-07-16',
    staffId: '3',
    staffName: 'Nusrat Jahan',
    clientId: '1',
    clientName: 'Apex Holdings Ltd.',
    jobId: '1',
    jobTitle: 'Statutory Audit FY 2025-26',
    taskId: '1',
    taskTitle: 'Drafting Planning Memorandum',
    workDescription: 'Worked on preliminary risk assessments and calculated the materiality threshold based on benchmark assets and revenues.',
    startTime: '09:00',
    endTime: '13:30',
    totalHours: 4.5,
    breakDuration: 0,
    billable: true,
    reviewStatus: 'Under Review',
    outcome: 'Completed Planning Memorandum draft and logged into the Review Queue.',
    supportingNote: 'Materiality calculated at 1.5% of gross revenues.',
  },
  {
    id: 'wl-2',
    date: '2026-07-16',
    staffId: '4',
    staffName: 'Sajid Ahmed',
    clientId: '3',
    clientName: 'Beximco Communications',
    jobId: '3',
    jobTitle: 'RJSC Annual Returns Filing',
    taskId: '4',
    taskTitle: 'Prepare RJSC Form XII filing',
    workDescription: 'Finalized the AGM minutes review and prepared the XML database mapping for NBR and RJSC Form XII filing portal.',
    startTime: '10:00',
    endTime: '16:00',
    totalHours: 6.0,
    breakDuration: 0,
    billable: true,
    reviewStatus: 'Approved Preview',
    outcome: 'RJSC Form XII is fully prepared for partner signature.',
  },
  {
    id: 'wl-3',
    date: '2026-07-15',
    staffId: '5',
    staffName: 'Tahmid Rahman',
    clientId: '1',
    clientName: 'Apex Holdings Ltd.',
    jobId: '1',
    jobTitle: 'Statutory Audit FY 2025-26',
    taskId: '2',
    taskTitle: 'Verifying Cash & Bank Balances',
    workDescription: 'Drafted 5 bank confirmation letters and updated the dispatch tracker sheet for Apex Holdings.',
    startTime: '13:00',
    endTime: '18:00',
    totalHours: 5.0,
    breakDuration: 0,
    billable: true,
    reviewStatus: 'Approved Preview',
    outcome: 'Dispatched confirmations to standard corporate branches.',
  }
];
